### ISSUE TITLE
弹窗嵌套时报错，导致内层弹窗永远无法打开了

### ISSUE THREAD

**Issue by andyyxw** [JinghuiS/vue-modal-provider#2]
场景: A 和 B 都是使用 `vue-modal-provider` 包装过的 Modal，单独使用没问题，如果在 A 里打开 B，关闭 B 时就会报错，此后 B 就再也无法打开了 无论是否还在 A 中操作，看报错是在 `resolve`  时框架内部崩了
![image](https://github.com/JinghuiS/vue-modal-provider/assets/41931722/921c4b28-ad4e-480e-b3ae-52d82ba18875)
![image](https://github.com/JinghuiS/vue-modal-provider/assets/41931722/dd9bcc22-4f1c-4b2a-a272-4e8827381771)

**Comment by JinghuiS** [comment]
更新最新版0.5.0试试

**Comment by andyyxw** [comment]
> 更新最新版0.5.0试试

验证ok了
